In [1]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt

In [96]:
np.random.randint(2,size=10000)

array([0, 0, 1, ..., 0, 1, 1])

In [188]:
np.random.choice([0,1],size=10000,p=[0.8,0.2]).mean()

0.2007

In [189]:
%matplotlib inline

In [201]:
# outcome of one coin flip
np.random.randint(2)

1

In [209]:
# outcomes of ten throusne coin flips 
np.random.randint(2,size=10000)

array([0, 0, 0, ..., 0, 1, 0])

In [214]:
# mean outcome of ten thousand coin flips 
np.random.randint(2, size=10000).mean()

0.4975

In [219]:
# outcome of one coin flip 
np.random.choice([0,1])

1

In [224]:
# mean outcome of then thousand coin flips 
np.random.choice([0,1],size=10000).mean()

0.5019

## 1. 2개 코인 던지기 두개 앞면 나와야됨

In [225]:
# 두개 동전을 백만번 던진다고?
tests = np.random.randint(2, size=(int(1e6),2))

In [226]:
tests

array([[1, 1],
       [1, 0],
       [1, 0],
       ...,
       [1, 1],
       [1, 0],
       [0, 1]])

In [227]:
# 백만번 던진 모든 테스트의 합계 
test_sums = tests.sum(axis=1)

In [231]:
test_sums

array([2, 1, 1, ..., 2, 1, 1])

In [232]:
# 정확히 두번 앞면이 나온거 확률 구하기 
(test_sums == 0).mean()

0.249842

### 3개 코인 던지고 정확히 한번만 앞면 나오는것

In [238]:
# 3개의 코인 백만번 던지기 
tests = np.random.randint(2, size=(int(1e6),3))

In [239]:
tests

array([[1, 0, 1],
       [0, 1, 1],
       [0, 1, 1],
       ...,
       [0, 1, 0],
       [0, 1, 1],
       [1, 1, 0]])

In [240]:
# 백만번 던진 모든 테스느 결과 
test_sums = tests.sum(axis=1)

In [241]:
test_sums

array([2, 2, 2, ..., 1, 2, 2])

In [244]:
# 정확히 한번 만 앞면 나온거 비율 잡아보기 
(test_sums == 1).mean()

0.375576

### 3개의 앞면나올 확률 0.6인거 정확히 한번만 앞면 나올거 구해라

In [248]:
tests = np.random.choice(2,size=(int(1e6),3),p=[0.6,0.4])

In [249]:
tests

array([[1, 0, 1],
       [0, 0, 1],
       [0, 0, 0],
       ...,
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [250]:
# sums of all tests 
test_sums = tests.sum(axis=1)

In [252]:
test_sums

array([2, 1, 0, ..., 0, 0, 0])

In [253]:
# 비율 
(test_sums == 1).mean()

0.431961

In [254]:
test = np.random.randint(2, size=(int(1e6),2))

In [256]:
test_sums = test.sum(axis=1)

In [257]:
(test_sums==2).mean()

0.250652

In [275]:
#Three fair coin flips produce exactly one head
test = np.random.randint(2, size=(int(1e6), 3))

In [276]:
test

array([[0, 1, 1],
       [1, 1, 1],
       [1, 1, 0],
       ...,
       [0, 1, 0],
       [0, 0, 0],
       [0, 1, 0]])

In [277]:
test_sum = test.sum(axis=1)
(test_sum == 2).mean()

0.375578

In [270]:
# Three biased coin flips with P(H) = 0.6 produce exactly one head

test = np.random.choice(2, size=(int(1e6),3),p=[0.6,0.4])

In [271]:
test_sums = test.sum(axis=1)

In [272]:
test_sums

array([0, 0, 2, ..., 1, 2, 1])

In [274]:
(test_sums==2).mean()

0.287435